spring:
  datasource:
    url: ${https://iiyxexrahfdntjdmwlnn.supabase.co}
    username: postgres
    password: ${J*/f57wPbpG*kEn}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true