spring:
  datasource:
    url: "jdbc:postgresql://db.your_project_id_on_supabase.supabase.co:5432/postgres?sslmode=require"
    username: "postgres"
    password: "your_password"   # quoted!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
